services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    network_mode: "host"
    command: ["tlslp-server"]      # server binds 127.0.0.1:1234

  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    network_mode: "host"
    environment:
      HOSTFULL_NAME: "localhost"
      PORT: "1234"
    command: ["tlslp-client"]      # client connects to 127.0.0.1:1234

