services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    network_mode: "host"
    command: ["tlslp-server"]
    environment:
      PYTHONUNBUFFERED: "1"

  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    network_mode: "host"
    depends_on:
      - server
    command: ["tlslp-client"]

